챕터3 개인과제/django_chapter3/my_first_pjt/accounts/urls.py
from django.urls import path
from . import views             # 이 곳은 accounts 앱의 URL 입니다.

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),  # 이 줄 추가
    path('profile/<str:username>/', views.profile, name='profile'),
]

챕터3 개인과제/django_chapter3/my_first_pjt/my_first_pjt/urls.py
""" 번역
    my_first_pjt 프로젝트의 URL 설정

urlpatterns 리스트는 URL들을 뷰로 라우팅합니다. 자세한 정보는 다음을 참고하세요:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/

예시들:
함수 기반 뷰
    1. 뷰를 임포트하기: from my_app import views
    2. urlpatterns에 URL 추가하기: path('', views.home, name='home')
클래스 기반 뷰
    1. 뷰를 임포트하기: from other_app.views import Home
    2. urlpatterns에 URL 추가하기: path('', Home.as_view(), name='home')
다른 URL 설정 포함하기
    1. include 함수 임포트하기: from django.urls import include, path
    2. urlpatterns에 URL 추가하기: path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from posts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

챕터3 개인과제/django_chapter3/my_first_pjt/posts/urls.py
from django.urls import path
from . import views             # 이 곳은 posts 앱의 URL 입니다.

app_name = 'posts'
urlpatterns = [
    path("", views.posts, name="posts"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:post_pk>/comments/", views.comment_create, name="comment_create"),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', 
        views.comment_delete, 
        name='comment_delete'
    ), 
    path("<int:pk>/like/", views.like, name="like"), 
    path("profile/", views.profile, name="profile"),
    path("post_confirm_delete/", views.post_confirm_delete, name="post_confirm_delete"),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', 
        views.comment_update, 
        name='comment_update'
    ),
]

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    followings = models.ManyToManyField(
        "self", related_name="followers", symmetrical=False
    ) # symmetrical=False 일촌 관계가 아닌 팔로우 관계

    

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/forms.py
from django.contrib.auth.forms import  UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from django.urls import reverse


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ()


class CustomUserChangeForm(UserChangeForm):


    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
            "email",
            ]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('accounts:change_password')}")
            self.fields["password"].help_text = password_help_text

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    PasswordChangeForm
)
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_http_methods
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth import get_user_model

@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get("next") or "index"
            return redirect(next_url)
        
    else:
        form = AuthenticationForm()

    context = {"form": form}
    return render(request, "accounts/login.html", context)

@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect("index")


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("index")
    else:
        form = CustomUserCreationForm()
    context = {"form": form}
    return render(request, "accounts/signup.html", context)

@require_POST
def delete(request): # 회원탈퇴
    if request.user.is_authenticated:
        request.user.delete() # auth_logout과 순서 바뀌면 안 됨
        auth_logout(request) # 로그아웃처럼 세션도 삭제
    return redirect("index")

@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, "accounts/update.html", context)


def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("index")
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, "accounts/change_password.html", context)

def profile(request, username):
    User = get_user_model()
    person = get_object_or_404(User, username=username)
    
    # 자신의 프로필이면 accounts/profile.html을, 다른 사람의 프로필이면 users/users.html을 보여줌
    if request.user.username == username:
        posts = person.posts.all()
        context = {
            'person': person,
            'posts': posts,
        }
        return render(request, 'accounts/profile.html', context)
    else:
        context = {
            'member': person,  # users.html에서 member로 사용중이므로 키 이름을 member로 변경
        }
        return render(request, 'users/users.html', context)

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<h1>비밀번호 변경</h1>

<form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">비밀번호 변경</button>
</form>

{% endblock content %}

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>로그인</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인" class="btn btn-primary">
</form>

{% endblock content %}

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">{{ person.username }}의 프로필</h1>
                </div>
                <div class="card-body">
                    <div class="profile-info mb-4">
                        <p><strong>가입일:</strong> {{ person.date_joined|date:"Y-m-d" }}</p>
                        <p><strong>팔로우:</strong> {{ person.followers.count }} <strong>팔로잉:</strong> {{ person.followings.count }}</p>
                        <p><strong>작성한 게시글</strong> {{ posts.count }} <strong>개</strong> </p>
                    </div>

                    <h4 class="mb-3">작성한 목록</h4>
                    <div class="user-posts">
                        {% for post in posts %}
                            <div class="card mb-3">
                                <div class="card-body">
                                    <h3 class="card-title">
                                        <a href="{% url 'posts:post_detail' post.pk %}" class="text-decoration-none">
                                            {{ post.title }}
                                        </a>
                                    </h3>
                                    <p class="card-text">
                                        <small class="text-muted">작성일: {{ post.created_at|date:"Y-m-d" }}</small>
                                    </p>
                                    <p class="card-text">
                                        <small class="text-muted">좋아요: {{ post.like_users.count }}</small>
                                        <small class="text-muted">댓글: {{ post.comments.count }}</small>
                                    </p>
                                </div>
                            </div>
                        {% empty %}
                            <p class="text-center">작성한 게시글이 없습니다.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            
            <div class="text-center mt-3">
                <a href="{% url 'posts:posts' %}" class="btn btn-primary">글 목록으로 돌아가기</a>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/templates/accounts/signup.html
{% extends "base.html"%}

{% block content%}
<h1>회원가입</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
</form>
{% endblock content %}

챕터3 개인과제/django_chapter3/my_first_pjt/accounts/templates/accounts/update.html
{% extends "base.html" %}

{% block content %}
    <h1>회원정보 수정</h1>

    <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="수정">
</form>

{% endblock content %}