챕터3 개인과제/django_chapter3/my_first_pjt/accounts/urls.py
from django.urls import path
from . import views             # 이 곳은 accounts 앱의 URL 입니다.

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("delete/", views.delete, name="delete"),
    path("update/", views.update, name="update"),
    path("password/", views.change_password, name="change_password"),  # 이 줄 추가
    path('profile/<str:username>/', views.profile, name='profile'),
]

챕터3 개인과제/django_chapter3/my_first_pjt/my_first_pjt/urls.py
""" 번역
    my_first_pjt 프로젝트의 URL 설정

urlpatterns 리스트는 URL들을 뷰로 라우팅합니다. 자세한 정보는 다음을 참고하세요:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/

예시들:
함수 기반 뷰
    1. 뷰를 임포트하기: from my_app import views
    2. urlpatterns에 URL 추가하기: path('', views.home, name='home')
클래스 기반 뷰
    1. 뷰를 임포트하기: from other_app.views import Home
    2. urlpatterns에 URL 추가하기: path('', Home.as_view(), name='home')
다른 URL 설정 포함하기
    1. include 함수 임포트하기: from django.urls import include, path
    2. urlpatterns에 URL 추가하기: path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from posts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("posts/", include("posts.urls")),
    path("users/", include("users.urls")),
    path("accounts/", include("accounts.urls")),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

챕터3 개인과제/django_chapter3/my_first_pjt/posts/urls.py
from django.urls import path
from . import views             # 이 곳은 posts 앱의 URL 입니다.

app_name = 'posts'
urlpatterns = [
    path("", views.posts, name="posts"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.post_detail, name="post_detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:post_pk>/comments/", views.comment_create, name="comment_create"),
    path('<int:post_pk>/comments/<int:comment_pk>/delete/', 
        views.comment_delete, 
        name='comment_delete'
    ), 
    path("<int:pk>/like/", views.like, name="like"), 
    path("profile/", views.profile, name="profile"),
    path("post_confirm_delete/", views.post_confirm_delete, name="post_confirm_delete"),
    path('<int:post_pk>/comments/<int:comment_pk>/update/', 
        views.comment_update, 
        name='comment_update'
    ),
]

챕터3 개인과제/django_chapter3/my_first_pjt/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/49ff3d30ab.js" crossorigin="anonymous"></script>
    <title>Document</title>    
    {% load static %}  <!-- static 추가 -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  <!-- css 스타일 추가 -->
    
    
    <!-- 스타일 적용 -->
    <style>
        body {
            background-color: black;
            color: white;
            
        }
    
        /* 기존 스타일 유지 */
        a {
            color: lightblue;
        }
    
        .navbar, .container {
            background-color: #2f2f2f;
            padding: 15px;
            border-radius: 10px; /* 모서리 둥글게 */
            margin: 20px; /* 좌우위아래 여백 추가 */
            opacity: 0.8; /*투명도 추가*/
            border: 3px solid #4fcaff; /* 테두리 추가 */

        }
    
        button, input[type="submit"] {
            background-color: #555;
            color: white;
            border: none;
            padding: 10px;
            cursor: pointer;
        }
    
        button:hover, input[type="submit"]:hover {
            background-color: #777;
        }
    
        html, body {
            margin: 0; /* 기본 여백 제거 */
            padding: 0; /* 기본 패딩 제거 */
            height: 100%; /* 전체 높이 사용 */
            width: 100%; /* 전체 너비 사용 */
        }

        .container-fluid {
            padding: 0; /* 컨테이너의 패딩 제거 */
            margin-left: 20px; /* 왼쪽 여백 추가 */
            margin-top: 20px;
        }
    
        /* 프로필 추가된 CSS */
        .profile-links {
            display: flex;
            align-items: center; /* 수직 정렬 */
            margin-left: auto; /* 오른쪽으로 정렬 */
        }
    
        .profile-links a, .profile-links input {
            margin-left: 10px; /* 링크와 버튼 사이의 간격 */
            white-space: nowrap; /* 줄바꿈 방지 */
        }

        .post-container {
            border: 1px solid rgb(47, 47, 47); /* 게시물 사이즈 만큼 선 추가*/
            border-radius: 5px; /* 모서리 둥글게 */
            padding: 15px; /* 패딩 추가 */
            margin-bottom: 30px; /* 아래 여백 추가 */
            margin-top: 20px;
            margin-right: 40px;
        }

        .post-title {
            margin-left: 3px;
            display: block; /* 제목을 인라인으로 설정하여 클릭 범위 줄이기 */
            cursor: pointer; /* 커서를 포인터로 변경하여 클릭 가능함을 표시 */
        }
            

        .post-image {
            width: 300px; /* 이미지 너비를 100%로 설정 */
            height: 100%; /* 비율 유지 */
            border-radius: 5px; /* 모서리 둥글게 */
        }


        .button-container {
            display: flex; /* 버튼을 가로로 나열 */
            gap: 0; /* 버튼 사이의 간격을 0으로 설정 */
            margin: 0; /* 여백 제거 */
            padding: 0; /* 패딩 제거 (필요에 따라 조정) */
            justify-content: center; /* 버튼을 중앙에 배치 */
        }

        .like-count {
            margin-left: -10px; /* 하트와 숫자 간의 간격 */
            color: white; /* 숫자 색상 */
            vertical-align: middle; /* 수직 정렬 */
            line-height: 1.5; /* 줄 높이 조정 (필요에 따라 조정) */
            padding-top: 2px; /* 숫자를 아래로 내리기 위한 패딩 추가 */
        }

            /* 새로운 글 작성 버튼 위치 조절 */
        .new-post-btn {
            margin-top: 10px;  /* 마지막 게시물과 새 글 작성 버튼 사이 간격 */
        }

        .user-profile-form {
            margin-left: 20px; /* 프로필 버튼 위치 조절 */
        }

        .follow-form {
            margin-top: 20px; /* 팔로우 버튼 위치 조절 */
            margin-bottom: 20px;
        }


    </style>
</head>
<!--여기까지 헤드 테마 적용 -->


<body>

    <div class="navbar d-flex justify-content-between">  <!-- d-flex와 justify-content-between 추가 -->
        <a href="{% url 'index' %}">
            <img src="{% static 'posts/fried_rice.png' %}" alt="홈" style="width: 70px; height: 50px;">
            <a href="{% url 'index' %}"><button class="btn btn-sm" style="color: #828282; margin-left: -10px;">Home</button></a>
        </a>

        
        <div class="profile-links">
            {% if request.user.is_authenticated %}
                <h3><span style="font-size: 25px;">안녕, {{ request.user.username }}</span></h3>
                <div class="user-profile-form"> 
                    <a href="{% url 'accounts:profile' request.user.username %}">
                        <button class="btn btn-primary btn-sm">프로필 보기</button> 
                    </a>
                </div>

                <a href="{% url 'accounts:update' %}">
                    <button class="btn btn-info btn-sm">회원정보 수정</button>
                </a>
                <form action="{% url 'accounts:logout' %}" method="POST" style="display:inline;">
                    {% csrf_token %}
                    <input type="submit" value="로그아웃" class="btn btn-danger btn-sm">  <!-- 부트스트랩 버튼 클래스 추가 -->
                </form>
                <form action="{% url "accounts:delete" %}" method="POST" style="display:inline;">
                    {% csrf_token %}
                    <input type="submit" value="회원탈퇴" class="btn btn-warning btn-sm">  <!-- 부트스트랩 버튼 클래스 추가 -->
                </form>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-sm">로그인</a>  <!-- 부트스트랩 버튼 클래스 추가 -->
                <a href="{% url 'accounts:signup' %}" class="btn btn-success btn-sm">회원가입</a>  <!-- 부트스트랩 버튼 클래스 추가 -->
            {% endif %}
        </div>
    </div>

    <div class="container-fluid">
        {% block content %}         
        {% endblock content %}      
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</body>
</html>